/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_Project_Scientific_Calculator;

import java.util.*;
  import java.awt.*;
import java.awt.event.*;
import static java.lang.Double.*;
import static java.lang.Integer.*;
import java.text.DecimalFormat;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author erikg
 */
public class Java_Project_Scientific_Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Java_Project_Scientific_Calculator
     */
    public Java_Project_Scientific_Calculator() {
        initComponents();
    }
    private boolean number = true;
    private String equalOp = "=";
    double num1;
    double num2;
    double answer;
    String operation = "";
    String input = "";
    double num = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jTextFieldInput = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonMultiplycation = new javax.swing.JButton();
        jButtonAddition = new javax.swing.JButton();
        jButtonSubtraction = new javax.swing.JButton();
        jButtonSin = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jRadioButtonRadian = new javax.swing.JRadioButton();
        jRadioButtonDegree = new javax.swing.JRadioButton();
        jLabelLastInput = new javax.swing.JLabel();
        jButtonSquared = new javax.swing.JButton();
        JLabelLastAnswer = new javax.swing.JLabel();
        jButtonTan = new javax.swing.JButton();
        jButtonSqrt = new javax.swing.JButton();
        jButtonSinh = new javax.swing.JButton();
        jButtonCosh = new javax.swing.JButton();
        jButtonTanh = new javax.swing.JButton();
        jButtonLn = new javax.swing.JButton();
        jButtonPi = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton0.setText("0");
        jButton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton0MouseClicked(evt);
            }
        });

        jButton1.setText("1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButtonDot.setText(".");
        jButtonDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDotMouseClicked(evt);
            }
        });

        jButtonEquals.setText("=");
        buttonGroup2.add(jButtonEquals);
        jButtonEquals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEqualsMouseClicked(evt);
            }
        });

        jTextFieldInput.setEditable(false);

        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });

        jButtonDivision.setText("/");
        buttonGroup2.add(jButtonDivision);
        jButtonDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDivisionMouseClicked(evt);
            }
        });

        jButtonMultiplycation.setText("X");
        buttonGroup2.add(jButtonMultiplycation);
        jButtonMultiplycation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMultiplycationMouseClicked(evt);
            }
        });

        jButtonAddition.setText("+");
        buttonGroup2.add(jButtonAddition);
        jButtonAddition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAdditionMouseClicked(evt);
            }
        });

        jButtonSubtraction.setText("-");
        buttonGroup2.add(jButtonSubtraction);
        jButtonSubtraction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubtractionMouseClicked(evt);
            }
        });

        jButtonSin.setText("Sin");
        buttonGroup2.add(jButtonSin);
        jButtonSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSinMouseClicked(evt);
            }
        });

        jButtonCos.setText("Cos");
        buttonGroup2.add(jButtonCos);
        jButtonCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCosMouseClicked(evt);
            }
        });

        jButtonLog.setText("Log");
        buttonGroup2.add(jButtonLog);
        jButtonLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioButtonRadian);
        jRadioButtonRadian.setText("Radian");

        buttonGroup1.add(jRadioButtonDegree);
        jRadioButtonDegree.setSelected(true);
        jRadioButtonDegree.setText("Degree");

        jLabelLastInput.setText("Last Input");

        jButtonSquared.setText("^");
        buttonGroup2.add(jButtonSquared);
        jButtonSquared.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSquaredMouseClicked(evt);
            }
        });

        JLabelLastAnswer.setText("Last Input");

        jButtonTan.setText("Tan");
        jButtonTan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTanMouseClicked(evt);
            }
        });

        jButtonSqrt.setText("√");
        jButtonSqrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSqrtMouseClicked(evt);
            }
        });

        jButtonSinh.setText("Sinh");
        jButtonSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSinhMouseClicked(evt);
            }
        });

        jButtonCosh.setText("Cosh");
        jButtonCosh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCoshMouseClicked(evt);
            }
        });

        jButtonTanh.setText("Tanh");
        jButtonTanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTanhMouseClicked(evt);
            }
        });

        jButtonLn.setText("Ln");
        jButtonLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLnMouseClicked(evt);
            }
        });

        jButtonPi.setText("π");
        jButtonPi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPiMouseClicked(evt);
            }
        });

        jButtonE.setText("e");
        jButtonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldInput)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEquals)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSubtraction)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSquared))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddition)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSqrt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMultiplycation)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSin))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDivision)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonTan)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonE)
                                    .addComponent(jButtonPi))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClear))
                    .addComponent(JLabelLastAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLastInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonRadian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDegree))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCosh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTanh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLn)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabelLastAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelLastInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRadian)
                    .addComponent(jRadioButtonDegree))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonDivision)
                    .addComponent(jButtonTan)
                    .addComponent(jButtonE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButtonMultiplycation)
                    .addComponent(jButtonSin)
                    .addComponent(jButtonPi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButtonAddition)
                    .addComponent(jButtonCos)
                    .addComponent(jButtonSqrt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDot)
                    .addComponent(jButton0)
                    .addComponent(jButtonEquals)
                    .addComponent(jButtonSubtraction)
                    .addComponent(jButtonLog)
                    .addComponent(jButtonSquared))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSinh)
                    .addComponent(jButtonCosh)
                    .addComponent(jButtonTanh)
                    .addComponent(jButtonLn))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String b = jButton1.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton0MouseClicked
        // TODO add your handling code here:
        String b = jButton0.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton0MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String b = jButton2.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String b = jButton3.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String b = jButton4.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String b = jButton5.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        String b = jButton6.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        String b = jButton7.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String b = jButton8.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        String b = jButton9.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButtonSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSinMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        if(jRadioButtonDegree.isSelected()){
            answer = Math.sin(Math.toRadians(num1));
        jTextFieldInput.setText("" + answer);
        }
        else if(jRadioButtonRadian.isSelected()){
            answer = Math.sin(num1);
        jTextFieldInput.setText("" + answer);
        }
        b = "Sin(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonSinMouseClicked

    private void jButtonCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCosMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        if(jRadioButtonDegree.isSelected()){
            answer = Math.cos(Math.toRadians(num1));
        jTextFieldInput.setText("" + answer);
        }
        else if(jRadioButtonRadian.isSelected()){
            answer = Math.cos(num1);
        jTextFieldInput.setText("" + answer);
        }
        b = "Cos(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonCosMouseClicked

    private void jButtonLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        
            answer = Math.log10(num1);
        jTextFieldInput.setText("" + answer);
        
        b = "Log(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonLogMouseClicked

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
        // TODO add your handling code here:
        jTextFieldInput.setText("");
        operation = "";
        num = 0;
        input="";
    }//GEN-LAST:event_jButtonClearMouseClicked

    private void jButtonDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDivisionMouseClicked
        // TODO add your handling code here:
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "/";
        jTextFieldInput.setText(s);
        num = 0;
        input="";}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");}
        
    }//GEN-LAST:event_jButtonDivisionMouseClicked

    private void jButtonMultiplycationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMultiplycationMouseClicked
        // TODO add your handling code here:
        String b;
        String s;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonMultiplycation.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "X";
        jTextFieldInput.setText(s);
        num = 0;
        input="";}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonMultiplycation.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "X");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonMultiplycation.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "X");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num2= parseInt(jTextFieldInput.getText());
        b = jButtonMultiplycation.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "X");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonMultiplycation.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "X");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonMultiplycation.getText();
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "X");
        }
        else{
        jTextFieldInput.setText("");
        jLabelLastInput.setText("error");}
    }//GEN-LAST:event_jButtonMultiplycationMouseClicked

    private void jButtonAdditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdditionMouseClicked
        // TODO add your handling code here:
        String b;
        String s;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonAddition.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "+";
        jTextFieldInput.setText(s);
        num = 0;
        input="";}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonAddition.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonAddition.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonAddition.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonAddition.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonAddition.getText();
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else{
        jTextFieldInput.setText("");
        jLabelLastInput.setText("error");}
    }//GEN-LAST:event_jButtonAdditionMouseClicked

    private void jButtonSubtractionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubtractionMouseClicked
        // TODO add your handling code here:
        String b;
        String s;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonSubtraction.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "-";
        jTextFieldInput.setText(s);
        num = 0;
        input="";}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSubtraction.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSubtraction.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSubtraction.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSubtraction.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "+");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSubtraction.getText();
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "-");
        }
        else{
        jTextFieldInput.setText("");
        jLabelLastInput.setText("error");}
    }//GEN-LAST:event_jButtonSubtractionMouseClicked

    private void jButtonEqualsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEqualsMouseClicked
        // TODO add your handling code here:
        
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "=";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = 0;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = 0;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = 0;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = 0;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = 0;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");}
    }//GEN-LAST:event_jButtonEqualsMouseClicked

    private void jButtonDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDotMouseClicked
        // TODO add your handling code here:
        String b = jButtonDot.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + b;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButtonDotMouseClicked

    private void jButtonSquaredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSquaredMouseClicked
        // TODO add your handling code here:
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "^";
        jTextFieldInput.setText(s);
        num = 0;
        input="";}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSquared.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "^");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSquared.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSquared.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSquared.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "/");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonSquared.getText();
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText(Double.toString(num1) + "^");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");}
        
    }//GEN-LAST:event_jButtonSquaredMouseClicked

    private void jButtonTanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTanMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        if(jRadioButtonDegree.isSelected()){
            answer = Math.tan(Math.toRadians(num1));
        jTextFieldInput.setText("" + answer);
        }
        else if(jRadioButtonRadian.isSelected()){
            answer = Math.tan(num1);
        jTextFieldInput.setText("" + answer);
        }
        b = "Tan(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonTanMouseClicked

    private void jButtonSqrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSqrtMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
            answer = Math.sqrt(num1);
        jTextFieldInput.setText("" + answer);
        b = "√(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonSqrtMouseClicked

    private void jButtonSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSinhMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        if(jRadioButtonDegree.isSelected()){
            answer = Math.sinh(Math.toRadians(num1));
        jTextFieldInput.setText("" + answer);
        }
        else if(jRadioButtonRadian.isSelected()){
            answer = Math.sinh(num1);
        jTextFieldInput.setText("" + answer);
        }
        b = "Sinh(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonSinhMouseClicked

    private void jButtonCoshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCoshMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        if(jRadioButtonDegree.isSelected()){
            answer = Math.cosh(Math.toRadians(num1));
        jTextFieldInput.setText("" + answer);
        }
        else if(jRadioButtonRadian.isSelected()){
            answer = Math.cosh(num1);
        jTextFieldInput.setText("" + answer);
        }
        b = "Cosh(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonCoshMouseClicked

    private void jButtonTanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTanhMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        if(jRadioButtonDegree.isSelected()){
            answer = Math.tanh(Math.toRadians(num1));
        jTextFieldInput.setText("" + answer);
        }
        else if(jRadioButtonRadian.isSelected()){
            answer = Math.tanh(num1);
        jTextFieldInput.setText("" + answer);
        }
        b = "Tanh(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonTanhMouseClicked

    private void jButtonLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLnMouseClicked
        // TODO add your handling code here:
        boolean n = true;
        String s;
        String b;
        if(!"".equals(jTextFieldInput.getText()) && ("".equals(operation) || "=".equals(operation) )){
        num= parseDouble(input);
        num1 = num;
        b = jButtonDivision.getText();
        s = jTextFieldInput.getText() + b;
        jTextFieldInput.setText(s);
        operation = "";
        jTextFieldInput.setText(s);
        num = 0;
        input="";
        jTextFieldInput.setText("");}
        else if(!"".equals(jTextFieldInput.getText()) && "-".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 - num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "+".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 + num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "X".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonEquals.getText();
        answer = num1 * num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "/".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = jButtonDivision.getText();
        answer = num1 / num2;
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = "";
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else if(!"".equals(jTextFieldInput.getText()) && "^".equals(operation)){
        num= parseDouble(input);
        num2 = num;
        b = "^";
        answer = Math.pow(num1, num2);
        s = Double.toString(answer) + b;
        jTextFieldInput.setText(s);
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(num1 + operation + num2 + "=" + answer);
        operation = b;
        jTextFieldInput.setText(s);
        num1 = answer;
        num = 0;
        input="";
        jTextFieldInput.setText("");
        }
        else{
        jTextFieldInput.setText("");
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText("error");
        n = false;}
        if(n == true){
        
            answer = Math.log(num1);
        jTextFieldInput.setText("" + answer);
        
        b = "Ln(" + num1 + ")=" + answer;
        JLabelLastAnswer.setText(jLabelLastInput.getText());
        jLabelLastInput.setText(b);
        num1 = answer;
        num = 0;
        input=""+num1;
        operation = "";
        jTextFieldInput.setText(""+num1);}
    }//GEN-LAST:event_jButtonLnMouseClicked

    private void jButtonPiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPiMouseClicked
        // TODO add your handling code here:
        String b = jButtonPi.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + Math.PI;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButtonPiMouseClicked

    private void jButtonEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEMouseClicked
        // TODO add your handling code here:
        String b = jButtonE.getText();
        String s = jTextFieldInput.getText() + b;
        input = input + Math.E;
        jTextFieldInput.setText(s);
    }//GEN-LAST:event_jButtonEMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_Project_Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_Project_Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_Project_Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_Project_Scientific_Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_Project_Scientific_Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLastAnswer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAddition;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonCosh;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonLn;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonMultiplycation;
    private javax.swing.JButton jButtonPi;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSinh;
    private javax.swing.JButton jButtonSqrt;
    private javax.swing.JButton jButtonSquared;
    private javax.swing.JButton jButtonSubtraction;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JButton jButtonTanh;
    private javax.swing.JLabel jLabelLastInput;
    private javax.swing.JRadioButton jRadioButtonDegree;
    private javax.swing.JRadioButton jRadioButtonRadian;
    private javax.swing.JTextField jTextFieldInput;
    // End of variables declaration//GEN-END:variables
}
